'use client'

// TO DO range of years
const yearOptions = [
  { value: '2026', label: '2026' },
  { value: '2025', label: '2025' },
  { value: '2024', label: '2024' },
  { value: '2023', label: '2023' },
  { value: '2022', label: '2022' },
  { value: '2021', label: '2021' },
  { value: '2020', label: '2020' },
  { value: '2019', label: '2019' },
  { value: '2018', label: '2018' },
  { value: '2017', label: '2017' },
  { value: '2016', label: '2016' },
  { value: '2015', label: '2015' },
  { value: '2014', label: '2014' },
  { value: '2013', label: '2013' },
  { value: '2012', label: '2012' },
  { value: '2011', label: '2011' },
  { value: '2010', label: '2010' },
  { value: '2009', label: '2009' },
  { value: '2008', label: '2008' },
  { value: '2007', label: '2007' },
  { value: '2006', label: '2006' },
  { value: '2005', label: '2005' },
  { value: '2004', label: '2004' },
  { value: '2003', label: '2003' },
  { value: '2002', label: '2002' },
  { value: '2001', label: '2001' },
  { value: '2000', label: '2000' },
  { value: '1999', label: '1999' },
  { value: '1998', label: '1998' },
  { value: '1997', label: '1997' },
  { value: '1996', label: '1996' },
  { value: '1995', label: '1995' },
  { value: '1994', label: '1994' },
  { value: '1993', label: '1993' },
  { value: '1992', label: '1992' },
  { value: '1991', label: '1991' },
  { value: '1990', label: '1990' },
  { value: '1989', label: '1989' },
  { value: '1988', label: '1988' },
  { value: '1987', label: '1987' },
  { value: '1986', label: '1986' },
  { value: '1985', label: '1985' },
  { value: '1984', label: '1984' },
  { value: '1983', label: '1983' },
  { value: '1982', label: '1982' },
  { value: '1981', label: '1981' },
  { value: '1980', label: '1980' },
  { value: '1979', label: '1979' },
  { value: '1978', label: '1978' },
  { value: '1977', label: '1977' },
  { value: '1976', label: '1976' },
  { value: '1975', label: '1975' },
  { value: '1974', label: '1974' },
  { value: '1973', label: '1973' },
  { value: '1972', label: '1972' },
  { value: '1971', label: '1971' },
  { value: '1970', label: '1970' },
  { value: '1969', label: '1969' },
  { value: '1968', label: '1968' },
  { value: '1967', label: '1967' },
  { value: '1966', label: '1966' },
  { value: '1965', label: '1965' },
  { value: '1964', label: '1964' },
  { value: '1963', label: '1963' },
  { value: '1962', label: '1962' },
  { value: '1961', label: '1961' },
  { value: '1960', label: '1960' },
  { value: '1959', label: '1959' },
  { value: '1958', label: '1958' },
  { value: '1957', label: '1957' },
  { value: '1956', label: '1956' },
  { value: '1955', label: '1955' },
  { value: '1954', label: '1954' },
  { value: '1953', label: '1953' },
  { value: '1952', label: '1952' },
  { value: '1951', label: '1951' },
  { value: '1950', label: '1950' },
];

const genreOptions = [
  { value: 'rock', label: 'Rock' },
  { value: 'electronic', label: 'Electronic' },
  { value: 'pop', label: 'Pop' },
  { value: 'funk-soul', label: 'Funk / Soul' },
  { value: 'folk-world-country', label: 'Folk / World / Country' },
  { value: 'jazz', label: 'Jazz' },
  { value: 'classical', label: 'Classical' },
  { value: 'hip-hop', label: 'Hip-Hop' },
  { value: 'reggae', label: 'Reggae' },
  { value: 'latin', label: 'Latin' },
  { value: 'blues', label: 'Blues' },
];

//automate this list with a hook
const styleOptions = [
  { value: 'AOR', label: 'AOR' },
  { value: 'Abstract', label: 'Abstract' },
  { value: 'Acid', label: 'Acid' },
  { value: 'Acid House', label: 'Acid House' },
  { value: 'Acid Jazz', label: 'Acid Jazz' },
  { value: 'Acid Rock', label: 'Acid Rock' },
  { value: 'Acoustic', label: 'Acoustic' },
  { value: 'African', label: 'African' },
  { value: 'Afro-Cuban', label: 'Afro-Cuban' },
  { value: 'Afro-Cuban Jazz', label: 'Afro-Cuban Jazz' },
  { value: 'Afrobeat', label: 'Afrobeat' },
  { value: 'Alt-Pop', label: 'Alt-Pop' },
  { value: 'Alternative Rock', label: 'Alternative Rock' },
  { value: 'Ambient', label: 'Ambient' },
  { value: 'Andean Music', label: 'Andean Music' },
  { value: 'Appalachian Music', label: 'Appalachian Music' },
  { value: 'Art Rock', label: 'Art Rock' },
  { value: 'Art Song', label: 'Art Song' },
  { value: 'Atmospheric Black Metal', label: 'Atmospheric Black Metal' },
  { value: 'Audiobook', label: 'Audiobook' },
  { value: 'Avant-garde Jazz', label: 'Avant-garde Jazz' },
  { value: 'Avantgarde', label: 'Avantgarde' },
  { value: 'Ballad', label: 'Ballad' },
  { value: 'Ballet', label: 'Ballet' },
  { value: 'Baroque', label: 'Baroque' },
  { value: 'Bass Music', label: 'Bass Music' },
  { value: 'Bayou Funk', label: 'Bayou Funk' },
  { value: 'Beat', label: 'Beat' },
  { value: 'Berlin-School', label: 'Berlin-School' },
  { value: 'Big Band', label: 'Big Band' },
  { value: 'Big Beat', label: 'Big Beat' },
  { value: 'Black Metal', label: 'Black Metal' },
  { value: 'Blackgaze', label: 'Blackgaze' },
  { value: 'Bluegrass', label: 'Bluegrass' },
  { value: 'Blues Rock', label: 'Blues Rock' },
  { value: 'Bolero', label: 'Bolero' },
  { value: 'Bomba', label: 'Bomba' },
  { value: 'Boogie', label: 'Boogie' },
  { value: 'Boom Bap', label: 'Boom Bap' },
  { value: 'Bop', label: 'Bop' },
  { value: 'Bossa Nova', label: 'Bossa Nova' },
  { value: 'Breakbeat', label: 'Breakbeat' },
  { value: 'Breakcore', label: 'Breakcore' },
  { value: 'Breaks', label: 'Breaks' },
  { value: 'Britcore', label: 'Britcore' },
  { value: 'Britpop', label: 'Britpop' },
  { value: 'Broken Beat', label: 'Broken Beat' },
  { value: 'Bubblegum', label: 'Bubblegum' },
  { value: 'Cajun', label: 'Cajun' },
  { value: 'Cantata', label: 'Cantata' },
  { value: 'Chanson', label: 'Chanson' },
  { value: 'Chicago Blues', label: 'Chicago Blues' },
  { value: 'Chillwave', label: 'Chillwave' },
  { value: 'Choral', label: 'Choral' },
  { value: 'Classic Rock', label: 'Classic Rock' },
  { value: 'Classical', label: 'Classical' },
  { value: 'Cloud Rap', label: 'Cloud Rap' },
  { value: 'Comedy', label: 'Comedy' },
  { value: 'Concert Film', label: 'Concert Film' },
  { value: 'Concerto', label: 'Concerto' },
  { value: 'Conscious', label: 'Conscious' },
  { value: 'Contemporary', label: 'Contemporary' },
  { value: 'Contemporary Jazz', label: 'Contemporary Jazz' },
  { value: 'Contemporary R&B', label: 'Contemporary R&B' },
  { value: 'Cool Jazz', label: 'Cool Jazz' },
  { value: 'Corrido', label: 'Corrido' },
  { value: 'Country', label: 'Country' },
  { value: 'Country Blues', label: 'Country Blues' },
  { value: 'Country Rock', label: 'Country Rock' },
  { value: 'Crust', label: 'Crust' },
  { value: 'Cut-up/DJ', label: 'Cut-up/DJ' },
  { value: 'DJ Battle Tool', label: 'DJ Battle Tool' },
  { value: 'Dance-pop', label: 'Dance-pop' },
  { value: 'Dancehall', label: 'Dancehall' },
  { value: 'Dark Ambient', label: 'Dark Ambient' },
  { value: 'Darkwave', label: 'Darkwave' },
  { value: 'Death Metal', label: 'Death Metal' },
  { value: 'Deep House', label: 'Deep House' },
  { value: 'Delta Blues', label: 'Delta Blues' },
  { value: 'Depressive Black Metal', label: 'Depressive Black Metal' },
  { value: 'Dialogue', label: 'Dialogue' },
  { value: 'Disco', label: 'Disco' },
  { value: 'Dixieland', label: 'Dixieland' },
  { value: 'Doo Wop', label: 'Doo Wop' },
  { value: 'Doom Metal', label: 'Doom Metal' },
  { value: 'Doomcore', label: 'Doomcore' },
  { value: 'Downtempo', label: 'Downtempo' },
  { value: 'Dream Pop', label: 'Dream Pop' },
  { value: 'Drone', label: 'Drone' },
  { value: 'Drum n Bass', label: 'Drum n Bass' },
  { value: 'Dub', label: 'Dub' },
  { value: 'Dub Techno', label: 'Dub Techno' },
  { value: 'Dubstep', label: 'Dubstep' },
  { value: 'Dungeon Synth', label: 'Dungeon Synth' },
  { value: 'EBM', label: 'EBM' },
  { value: 'Easy Listening', label: 'Easy Listening' },
  { value: 'Educational', label: 'Educational' },
  { value: 'Electric Blues', label: 'Electric Blues' },
  { value: 'Electro', label: 'Electro' },
  { value: 'Electro House', label: 'Electro House' },
  { value: 'Electroclash', label: 'Electroclash' },
  { value: 'Emo', label: 'Emo' },
  { value: 'Erotic', label: 'Erotic' },
  { value: 'Ethereal', label: 'Ethereal' },
  { value: 'Euro House', label: 'Euro House' },
  { value: 'Eurodance', label: 'Eurodance' },
  { value: 'Europop', label: 'Europop' },
  { value: 'Experimental', label: 'Experimental' },
  { value: 'Fado', label: 'Fado' },
  { value: 'Field Recording', label: 'Field Recording' },
  { value: 'Folk', label: 'Folk' },
  { value: 'Folk Metal', label: 'Folk Metal' },
  { value: 'Folk Rock', label: 'Folk Rock' },
  { value: 'Footwork', label: 'Footwork' },
  { value: 'Free Improvisation', label: 'Free Improvisation' },
  { value: 'Free Jazz', label: 'Free Jazz' },
  { value: 'Freestyle', label: 'Freestyle' },
  { value: 'Freetekno', label: 'Freetekno' },
  { value: 'Funeral Doom Metal', label: 'Funeral Doom Metal' },
  { value: 'Funk', label: 'Funk' },
  { value: 'Funk Metal', label: 'Funk Metal' },
  { value: 'Fusion', label: 'Fusion' },
  { value: 'Future Jazz', label: 'Future Jazz' },
  { value: 'Gabber', label: 'Gabber' },
  { value: 'Gangsta', label: 'Gangsta' },
  { value: 'Garage House', label: 'Garage House' },
  { value: 'Garage Rock', label: 'Garage Rock' },
  { value: 'Glam', label: 'Glam' },
  { value: 'Glitch', label: 'Glitch' },
  { value: 'Goa Trance', label: 'Goa Trance' },
  { value: 'Goregrind', label: 'Goregrind' },
  { value: 'Gospel', label: 'Gospel' },
  { value: 'Goth Rock', label: 'Goth Rock' },
  { value: 'Gothic Metal', label: 'Gothic Metal' },
  { value: 'Grime', label: 'Grime' },
  { value: 'Grindcore', label: 'Grindcore' },
  { value: 'Groove Metal', label: 'Groove Metal' },
  { value: 'Grunge', label: 'Grunge' },
  { value: 'Halftime', label: 'Halftime' },
  { value: 'Happy Hardcore', label: 'Happy Hardcore' },
  { value: 'Hard Bop', label: 'Hard Bop' },
  { value: 'Hard House', label: 'Hard House' },
  { value: 'Hard Rock', label: 'Hard Rock' },
  { value: 'Hard Techno', label: 'Hard Techno' },
  { value: 'Hard Trance', label: 'Hard Trance' },
  { value: 'Hardcore', label: 'Hardcore' },
  { value: 'Hardcore Hip-Hop', label: 'Hardcore Hip-Hop' },
  { value: 'Hardstyle', label: 'Hardstyle' },
  { value: 'Heavy Metal', label: 'Heavy Metal' },
  { value: 'Hi NRG', label: 'Hi NRG' },
  { value: 'Hip Hop', label: 'Hip Hop' },
  { value: 'Hip-House', label: 'Hip-House' },
  { value: 'Holiday', label: 'Holiday' },
  { value: 'House', label: 'House' },
  { value: 'IDM', label: 'IDM' },
  { value: 'Impressionist', label: 'Impressionist' },
  { value: 'Indie Pop', label: 'Indie Pop' },
  { value: 'Indie Rock', label: 'Indie Rock' },
  { value: 'Industrial', label: 'Industrial' },
  { value: 'Instrumental', label: 'Instrumental' },
  { value: 'Interview', label: 'Interview' },
  { value: 'Italo House', label: 'Italo House' },
  { value: 'Italo-Disco', label: 'Italo-Disco' },
  { value: 'Italodance', label: 'Italodance' },
  { value: 'Jangle Pop', label: 'Jangle Pop' },
  { value: 'Jazz-Funk', label: 'Jazz-Funk' },
  { value: 'Jazz-Rock', label: 'Jazz-Rock' },
  { value: 'Jazzdance', label: 'Jazzdance' },
  { value: 'Jazzy Hip-Hop', label: 'Jazzy Hip-Hop' },
  { value: 'Jumpstyle', label: 'Jumpstyle' },
  { value: 'Jungle', label: 'Jungle' },
  { value: 'Kayōkyoku', label: 'Kayōkyoku' },
  { value: 'Klezmer', label: 'Klezmer' },
  { value: 'Krautrock', label: 'Krautrock' },
  { value: 'Latin', label: 'Latin' },
  { value: 'Latin Jazz', label: 'Latin Jazz' },
  { value: 'Latin Pop', label: 'Latin Pop' },
  { value: 'Leftfield', label: 'Leftfield' },
  { value: 'Levenslied', label: 'Levenslied' },
  { value: 'Lo-Fi', label: 'Lo-Fi' },
  { value: 'Lounge', label: 'Lounge' },
  { value: 'Lovers Rock', label: 'Lovers Rock' },
  { value: 'Makina', label: 'Makina' },
  { value: 'Mambo', label: 'Mambo' },
  { value: 'Mass', label: 'Mass' },
  { value: 'Math Rock', label: 'Math Rock' },
  { value: 'Melodic Death Metal', label: 'Melodic Death Metal' },
  { value: 'Melodic Hardcore', label: 'Melodic Hardcore' },
  { value: 'Mento', label: 'Mento' },
  { value: 'Metalcore', label: 'Metalcore' },
  { value: 'Minimal', label: 'Minimal' },
  { value: 'Minimal Techno', label: 'Minimal Techno' },
  { value: 'Mod', label: 'Mod' },
  { value: 'Modal', label: 'Modal' },
  { value: 'Modern', label: 'Modern' },
  { value: 'Modern Classical', label: 'Modern Classical' },
  { value: 'Modern Electric Blues', label: 'Modern Electric Blues' },
  { value: 'Monolog', label: 'Monolog' },
  { value: 'Musique Concrète', label: 'Musique Concrète' },
  { value: 'Neo Soul', label: 'Neo Soul' },
  { value: 'Neo-Classical', label: 'Neo-Classical' },
  { value: 'Neo-Romantic', label: 'Neo-Romantic' },
  { value: 'Neofolk', label: 'Neofolk' },
  { value: 'New Beat', label: 'New Beat' },
  { value: 'New Jack Swing', label: 'New Jack Swing' },
  { value: 'New Wave', label: 'New Wave' },
  { value: 'No Wave', label: 'No Wave' },
  { value: 'Noise', label: 'Noise' },
  { value: 'Noise Rock', label: 'Noise Rock' },
  { value: 'Noisecore', label: 'Noisecore' },
  { value: 'Nordic', label: 'Nordic' },
  { value: 'Novelty', label: 'Novelty' },
  { value: 'Nu Metal', label: 'Nu Metal' },
  { value: 'Nu-Disco', label: 'Nu-Disco' },
  { value: 'Nursery Rhymes', label: 'Nursery Rhymes' },
  { value: 'Oi', label: 'Oi' },
  { value: 'Opera', label: 'Opera' },
  { value: 'Oratorio', label: 'Oratorio' },
  { value: 'Orchestra', label: 'Orchestra' },
  { value: 'Parody', label: 'Parody' },
  { value: 'Piano', label: 'Piano' },
  { value: 'Piano Blues', label: 'Piano Blues' },
  { value: 'Poetry', label: 'Poetry' },
  { value: 'Pop Punk', label: 'Pop Punk' },
  { value: 'Pop Rap', label: 'Pop Rap' },
  { value: 'Pop Rock', label: 'Pop Rock' },
  { value: 'Pornogrind', label: 'Pornogrind' },
  { value: 'Post Bop', label: 'Post Bop' },
  { value: 'Post Rock', label: 'Post Rock' },
  { value: 'Post-Hardcore', label: 'Post-Hardcore' },
  { value: 'Post-Metal', label: 'Post-Metal' },
  { value: 'Post-Punk', label: 'Post-Punk' },
  { value: 'Power Electronics', label: 'Power Electronics' },
  { value: 'Power Metal', label: 'Power Metal' },
  { value: 'Power Pop', label: 'Power Pop' },
  { value: 'Power Violence', label: 'Power Violence' },
  { value: 'Prog Rock', label: 'Prog Rock' },
  { value: 'Progressive House', label: 'Progressive House' },
  { value: 'Progressive Metal', label: 'Progressive Metal' },
  { value: 'Progressive Trance', label: 'Progressive Trance' },
  { value: 'Psy-Trance', label: 'Psy-Trance' },
  { value: 'Psychedelic', label: 'Psychedelic' },
  { value: 'Psychedelic Rock', label: 'Psychedelic Rock' },
  { value: 'Psychobilly', label: 'Psychobilly' },
  { value: 'Pub Rock', label: 'Pub Rock' },
  { value: 'Punk', label: 'Punk' },
  { value: 'Ragtime', label: 'Ragtime' },
  { value: 'Reggae', label: 'Reggae' },
  { value: 'Reggae-Pop', label: 'Reggae-Pop' },
  { value: 'Religious', label: 'Religious' },
  { value: 'Renaissance', label: 'Renaissance' },
  { value: 'Rhythm & Blues', label: 'Rhythm & Blues' },
  { value: 'Rhythmic Noise', label: 'Rhythmic Noise' },
  { value: 'RnB/Swing', label: 'RnB/Swing' },
  { value: 'Rock & Roll', label: 'Rock & Roll' },
  { value: 'Rockabilly', label: 'Rockabilly' },
  { value: 'Rocksteady', label: 'Rocksteady' },
  { value: 'Romantic', label: 'Romantic' },
  { value: 'Roots Reggae', label: 'Roots Reggae' },
  { value: 'Salsa', label: 'Salsa' },
  { value: 'Samba', label: 'Samba' },
  { value: 'Schlager', label: 'Schlager' },
  { value: 'Score', label: 'Score' },
  { value: 'Shoegaze', label: 'Shoegaze' },
  { value: 'Ska', label: 'Ska' },
  { value: 'Slowcore', label: 'Slowcore' },
  { value: 'Sludge Metal', label: 'Sludge Metal' },
  { value: 'Smooth Jazz', label: 'Smooth Jazz' },
  { value: 'Soca', label: 'Soca' },
  { value: 'Soft Rock', label: 'Soft Rock' },
  { value: 'Sonata', label: 'Sonata' },
  { value: 'Soul', label: 'Soul' },
  { value: 'Soul-Jazz', label: 'Soul-Jazz' },
  { value: 'Soundtrack', label: 'Soundtrack' },
  { value: 'Southern Rock', label: 'Southern Rock' },
  { value: 'Space Rock', label: 'Space Rock' },
  { value: 'Space-Age', label: 'Space-Age' },
  { value: 'Speed Metal', label: 'Speed Metal' },
  { value: 'Speedcore', label: 'Speedcore' },
  { value: 'Spirituals', label: 'Spirituals' },
  { value: 'Spoken Word', label: 'Spoken Word' },
  { value: 'Steel Band', label: 'Steel Band' },
  { value: 'Stoner Rock', label: 'Stoner Rock' },
  { value: 'Story', label: 'Story' },
  { value: 'Surf', label: 'Surf' },
  { value: 'Swing', label: 'Swing' },
  { value: 'Symphonic Metal', label: 'Symphonic Metal' },
  { value: 'Symphonic Rock', label: 'Symphonic Rock' },
  { value: 'Synth-pop', label: 'Synth-pop' },
  { value: 'Synthwave', label: 'Synthwave' },
  { value: 'Tech House', label: 'Tech House' },
  { value: 'Technical Death Metal', label: 'Technical Death Metal' },
  { value: 'Techno', label: 'Techno' },
  { value: 'Texas Blues', label: 'Texas Blues' },
  { value: 'Theme', label: 'Theme' },
  { value: 'Thrash', label: 'Thrash' },
  { value: 'Toasting', label: 'Toasting' },
  { value: 'Trance', label: 'Trance' },
  { value: 'Trap', label: 'Trap' },
  { value: 'Tribal', label: 'Tribal' },
  { value: 'Tribal House', label: 'Tribal House' },
  { value: 'Trip Hop', label: 'Trip Hop' },
  { value: 'Turntablism', label: 'Turntablism' },
  { value: 'Twist', label: 'Twist' },
  { value: 'UK Garage', label: 'UK Garage' },
  { value: 'Vaporwave', label: 'Vaporwave' },
  { value: 'Video Game Music', label: 'Video Game Music' },
  { value: 'Viking Metal', label: 'Viking Metal' },
  { value: 'Vocal', label: 'Vocal' },
  { value: 'Éntekhno', label: 'Éntekhno' },
];

export { yearOptions, genreOptions, styleOptions };